const PATCH_CORD_SEGMENTS = 10;
const FORCE_Y = 2000;
const FORCE_Y_STRENGTH = 0.005;
const FORCE_COLLIDE = 20;
const FORCE_LINK_STRENGTH = 0.9;

export {
  PATCH_CORD_SEGMENTS,
  FORCE_Y,
  FORCE_Y_STRENGTH,
  FORCE_COLLIDE,
  FORCE_LINK_STRENGTH,
};
